### ISSUE TITLE
Why the weird azimuth coordinate system?

### ISSUE THREAD

**Issue by acannon828** [greekgoddj/mit-hrtf-lib#1]
> "azimuth" is in the range of [-180, 180] degrees, where position 0 is the centre in front of the listener, negative values are to the left of the listener, and positive values are to the right of the front centre.

Why? Why not just use the standard unit circle, i.e. if 0 is front of the listener, [0, 180] is to the left and [-180, 0] is to the right?

**Comment by greekgoddj** [comment]
A good question, for which I don't have a good answer. I suppose I had a reason all those years ago when I started it. If I was writing it again, I would go with the popular convention.
